export const mockShops = [
  {
    _id: 'shop_1',
    owner: 'user_seller_1',
    name: 'The Iron Loom',
    description: 'Forging heritage into every thread. We specialize in heavy-gauge industrial weaving techniques blended with traditional patterns from the southern highlands.',
    category: 'Textiles',
    coverUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=400&q=80',
    location: { type: 'Point', coordinates: [125.6128, 7.0731] },
    address: 'Davao City, Davao del Sur',
    isActive: true,
    rating: 4.9
  },
  {
    _id: 'shop_2',
    owner: 'user_seller_2',
    name: 'Maranao Woodworks',
    description: 'Exquisite okir wood carvings and handcrafted furniture that bring the rich history of Mindanao into your modern home. Master craftsmen preserve centuries of wood sculpting.',
    category: 'Woodwork',
    coverUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=1200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400&q=80',
    location: { type: 'Point', coordinates: [124.2863, 8.0210] },
    address: 'Marawi City, Lanao del Sur',
    isActive: true,
    rating: 3.9
  },
  {
    _id: 'shop_3',
    owner: 'user_seller_3',
    name: 'Isla Pottery',
    description: 'Hand-thrown ceramics made from locally sourced clay, baked in wood-fired kilns for a unique, earthy finish. Every piece tells the story of the earth it came from.',
    category: 'Ceramics',
    coverUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1578500494198-246f612b3b3d?w=400&q=80',
    location: { type: 'Point', coordinates: [124.6461, 8.4822] },
    address: 'Cagayan de Oro, Misamis Oriental',
    isActive: true,
    rating: 4.7
  },
  {
    _id: 'shop_4',
    owner: 'user_seller_4',
    name: 'Lumad Metalcraft',
    description: 'Hand-forged brass and copper works inspired by ancestral Lumad patterns. Each piece is fire-tempered using traditional bellows techniques passed down through generations.',
    category: 'Metalwork',
    coverUrl: 'https://images.unsplash.com/photo-1571898223901-5ff77a0f7af5?w=1200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&q=80',
    location: { type: 'Point', coordinates: [125.1716, 6.1164] },
    address: 'General Santos City, South Cotabato',
    isActive: true,
    rating: 3.2
  },
  {
    _id: 'shop_5',
    owner: 'user_seller_5',
    name: 'Agusan Rattan Guild',
    description: 'Handcrafted rattan and bamboo furniture, combining tribal Agusan patterns with modern minimalist design.',
    category: 'Woodwork',
    coverUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=1200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&q=80',
    location: { type: 'Point', coordinates: [125.5392, 8.9475] },
    address: 'Butuan City, Agusan del Norte',
    isActive: true,
    rating: 4.8
  },
  {
    _id: 'shop_6',
    owner: 'user_seller_6',
    name: 'Yakan Heritage Weavers',
    description: 'Authentic Yakan handwoven textiles featuring striking geometric patterns and bold colors, handmade by master weavers from Basilan and Zamboanga.',
    category: 'Textiles',
    coverUrl: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=1200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&q=80',
    location: { type: 'Point', coordinates: [122.0790, 6.9214] },
    address: 'Zamboanga City, Zamboanga del Sur',
    isActive: true,
    rating: 4.9
  },
  {
    _id: 'shop_7',
    owner: 'user_seller_7',
    name: 'Inaul Legacy Textiles',
    description: 'Preserving the legacy of the Maguindanaon Inaul. Exquisite handwoven silk fabrics featuring vibrant, royal colors and traditional geometric grids.',
    category: 'Textiles',
    coverUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=1200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&q=80',
    location: { type: 'Point', coordinates: [124.2422, 7.2207] },
    address: 'Cotabato City, Maguindanao',
    isActive: true,
    rating: 4.6
  },
  {
    _id: 'shop_8',
    owner: 'user_seller_8',
    name: 'Maria Cristina Metal Arts',
    description: 'Master blacksmiths crafting legendary steel bolos, Kampilan swords, and custom carbon steel kitchen blades. Heavy-duty utility meets ancestral artistry.',
    category: 'Metalwork',
    coverUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=400&q=80',
    location: { type: 'Point', coordinates: [124.2405, 8.2280] },
    address: 'Iligan City, Lanao del Norte',
    isActive: true,
    rating: 4.5
  },
];

export const mockProducts = [
  // ── The Iron Loom (shop_1) ──────────────────────────────────────────────
  {
    _id: 'prod_1',
    shop: 'shop_1',
    name: 'Ochre Highlands Scarf',
    description: 'A beautifully patterned handwoven scarf featuring natural cotton and silk blends. Hand-dyed using organic highland flora.',
    price: 18500,
    category: 'Scarves',
    imageUrl: 'https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?w=800&q=80',
    inStock: true,
    colors: ['Natural Ochre', 'Slate Grey', 'Deep Rust'],
    sizes: ['S / 60×90cm', 'M / 80×120cm', 'L / 100×150cm'],
    rating: 4.9,
    reviewCount: 42,
    stockQuantity: 15,
  },
  {
    _id: 'prod_2',
    shop: 'shop_1',
    name: 'Iron Slate Runner',
    description: 'A heavy-weight runner blending hemp and steel-thread accents. Perfect for industrial-chic dining settings.',
    price: 24000,
    category: 'Runners',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    inStock: true,
    colors: ['Slate Grey', 'Coal Black'],
    sizes: ['M / 40×150cm', 'L / 40×200cm'],
    rating: 4.8,
    reviewCount: 28,
    stockQuantity: 8,
  },
  {
    _id: 'prod_3',
    shop: 'shop_1',
    name: 'Desert Loom Blanket',
    description: 'Cozy and oversized, this natural alpaca blend blanket features hand-tied tassels and intricate geometric patterns.',
    price: 32000,
    category: 'Blankets',
    imageUrl: 'https://images.unsplash.com/photo-1612160609504-334bce3fc71e?w=800&q=80',
    inStock: true,
    colors: ['Desert Sand', 'Terracotta', 'Sage'],
    sizes: ['Queen', 'King'],
    rating: 5.0,
    reviewCount: 19,
    stockQuantity: 5,
  },

  // ── Maranao Woodworks (shop_2) ──────────────────────────────────────────
  {
    _id: 'prod_4',
    shop: 'shop_2',
    name: 'Okir Carved Baul',
    description: 'A traditional wooden chest adorned with intricate okir motifs. Perfect for storing heirlooms and valuables.',
    price: 850000,
    category: 'Storage',
    imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80',
    inStock: true,
    colors: ['Dark Mahogany', 'Natural Nara'],
    sizes: ['Medium', 'Large'],
    rating: 4.9,
    reviewCount: 12,
    stockQuantity: 2,
  },
  {
    _id: 'prod_5',
    shop: 'shop_2',
    name: 'Mahogany Lounge Chair',
    description: 'A low-slung lounge chair carved from single pieces of sustainably sourced mahogany. Smooth, organic curves.',
    price: 1200000,
    category: 'Furniture',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    inStock: true,
    colors: ['Cherry Mahogany', 'Espresso'],
    sizes: ['Standard'],
    rating: 4.7,
    reviewCount: 31,
    stockQuantity: 4,
  },
  {
    _id: 'prod_6',
    shop: 'shop_2',
    name: 'Kulintang Stand',
    description: 'Hand-carved wooden stand designed for traditional kulintang gongs. Features elegant swooping lines.',
    price: 450000,
    category: 'Instruments',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&q=80',
    inStock: false,
    colors: ['Red Lauan', 'Golden Yakal'],
    sizes: ['Standard 8-Gong'],
    rating: 4.9,
    reviewCount: 9,
    stockQuantity: 0,
  },

  // ── Isla Pottery (shop_3) ───────────────────────────────────────────────
  {
    _id: 'prod_7',
    shop: 'shop_3',
    name: 'Speckled Coffee Mug',
    description: 'A charming, imperfectly round coffee mug with a rustic speckled glaze. Holds about 300 ml.',
    price: 65000,
    category: 'Drinkware',
    imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80',
    inStock: true,
    colors: ['Speckled White', 'Celadon Green', 'Iron Blue'],
    sizes: ['300ml', '450ml'],
    rating: 4.9,
    reviewCount: 128,
    stockQuantity: 45,
  },
  {
    _id: 'prod_8',
    shop: 'shop_3',
    name: 'Terracotta Planter',
    description: 'Large terracotta pot ideal for indoor monsteras or outdoor ferns. Hand-thrown and naturally porous.',
    price: 120000,
    category: 'Garden',
    imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80',
    inStock: true,
    colors: ['Classic Clay', 'Whitewash'],
    sizes: ['8-inch', '10-inch', '12-inch'],
    rating: 4.6,
    reviewCount: 54,
    stockQuantity: 22,
  },
  {
    _id: 'prod_9',
    shop: 'shop_3',
    name: 'Matte Charcoal Vase',
    description: 'A minimalist vase with a dark, matte charcoal finish. Perfect for dried flowers or standalone display.',
    price: 95000,
    category: 'Decor',
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&q=80',
    inStock: true,
    colors: ['Matte Charcoal', 'Sandstone'],
    sizes: ['Small', 'Medium', 'Large'],
    rating: 4.8,
    reviewCount: 67,
    stockQuantity: 14,
  },

  // ── Lumad Metalcraft (shop_4) ───────────────────────────────────────────
  {
    _id: 'prod_10',
    shop: 'shop_4',
    name: 'Hammered Copper Bowl',
    description: 'A statement serving bowl hand-hammered from a single sheet of copper. Food-safe lacquer interior with a raw patina exterior.',
    price: 185000,
    category: 'Kitchenware',
    imageUrl: 'https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=800&q=80',
    inStock: true,
    colors: ['Raw Copper', 'Aged Patina'],
    sizes: ['Small', 'Medium'],
    rating: 4.8,
    reviewCount: 36,
    stockQuantity: 12,
  },
  {
    _id: 'prod_11',
    shop: 'shop_4',
    name: 'Brass Wind Chime',
    description: 'Melodic brass tubes tuned to a pentatonic scale, suspended from a hand-carved driftwood hanger.',
    price: 95000,
    category: 'Decor',
    imageUrl: 'https://images.unsplash.com/photo-1534126511673-b6899657816a?w=800&q=80',
    inStock: true,
    colors: ['Polished Brass', 'Antique Bronze'],
    sizes: ['Standard'],
    rating: 4.7,
    reviewCount: 22,
    stockQuantity: 18,
  },
  {
    _id: 'prod_12',
    shop: 'shop_4',
    name: 'Forged Iron Candle Holder',
    description: 'A dramatic three-arm candelabra forged from raw iron with twisted vine detailing. Perfect centerpiece for rustic dining.',
    price: 320000,
    category: 'Lighting',
    imageUrl: 'https://images.unsplash.com/photo-1512238972498-ef2bd6f24df0?w=800&q=80',
    inStock: false,
    colors: ['Matte Black', 'Rust Finish'],
    sizes: ['3-Arm', '5-Arm'],
    rating: 4.9,
    reviewCount: 15,
    stockQuantity: 0,
  },

  // ── Agusan Rattan Guild (shop_5) ─────────────────────────────────────────
  {
    _id: 'prod_13',
    shop: 'shop_5',
    name: 'Agusan Rattan Armchair',
    description: 'Sleek, lightweight rattan armchair featuring traditional weaving patterns on the backrest. Excellent durability.',
    price: 550000,
    category: 'Furniture',
    imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80',
    inStock: true,
    colors: ['Natural Tan', 'Honey Brown'],
    sizes: ['Standard'],
    rating: 4.8,
    reviewCount: 14,
    stockQuantity: 6,
  },
  {
    _id: 'prod_14',
    shop: 'shop_5',
    name: 'Bamboo Nesting Tables',
    description: 'Set of three minimalist nesting tables constructed from solid, sustainable structural bamboo.',
    price: 320000,
    category: 'Furniture',
    imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=800&q=80',
    inStock: true,
    colors: ['Natural Bamboo', 'Carbonized Dark'],
    sizes: ['Set of 3'],
    rating: 4.7,
    reviewCount: 9,
    stockQuantity: 8,
  },

  // ── Yakan Heritage Weavers (shop_6) ──────────────────────────────────────
  {
    _id: 'prod_15',
    shop: 'shop_6',
    name: 'Yakan Seputangan Tapestry',
    description: 'A masterpiece of Yakan weaving, this tight geometric cotton tapestry can be styled as a table centerpiece or wall art.',
    price: 450000,
    category: 'Decor',
    imageUrl: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=800&q=80',
    inStock: true,
    colors: ['Multicolor Bold', 'Harvest Autumn'],
    sizes: ['100×100cm'],
    rating: 5.0,
    reviewCount: 22,
    stockQuantity: 3,
  },
  {
    _id: 'prod_16',
    shop: 'shop_6',
    name: 'Geometric Table Runner',
    description: 'Introduce color and heritage with this heavy Yakan weave runner. Handloomed over three weeks.',
    price: 180000,
    category: 'Decor',
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80',
    inStock: true,
    colors: ['Primary Red/Yellow', 'Teal/Copper'],
    sizes: ['35×180cm'],
    rating: 4.8,
    reviewCount: 17,
    stockQuantity: 12,
  },

  // ── Inaul Legacy Textiles (shop_7) ───────────────────────────────────────
  {
    _id: 'prod_17',
    shop: 'shop_7',
    name: 'Royal Purple Inaul Malong',
    description: 'Traditional Maguindanaon tubular garment handwoven in premium silk threads with golden metallic highlights.',
    price: 500000,
    category: 'Clothing',
    imageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&q=80',
    inStock: true,
    colors: ['Royal Purple & Gold', 'Emerald & Bronze'],
    sizes: ['One Size (Tubular)'],
    rating: 4.9,
    reviewCount: 11,
    stockQuantity: 4,
  },
  {
    _id: 'prod_18',
    shop: 'shop_7',
    name: 'Golden Weave Inaul Sash',
    description: 'A ceremonial sash highlighting the intricate checkered and floral patterns native to Cotabato weaving.',
    price: 120000,
    category: 'Accessories',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    inStock: true,
    colors: ['Crimson & Gold', 'Slate & Gold'],
    sizes: ['15×150cm'],
    rating: 4.5,
    reviewCount: 8,
    stockQuantity: 15,
  },

  // ── Maria Cristina Metal Arts (shop_8) ───────────────────────────────────
  {
    _id: 'prod_19',
    shop: 'shop_8',
    name: 'Hand-Forged Carbon Steel Bolo',
    description: 'A heavy-duty agricultural and utility blade forged from spring steel with a Kamagong hardwood handle.',
    price: 250000,
    category: 'Tools',
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80',
    inStock: true,
    colors: ['Natural Steel'],
    sizes: ['12-inch Blade', '14-inch Blade'],
    rating: 4.7,
    reviewCount: 33,
    stockQuantity: 7,
  },
  {
    _id: 'prod_20',
    shop: 'shop_8',
    name: 'Damascus Steel Chef Knife',
    description: 'Precision kitchen knife showing beautiful ripple patterns of layered high-carbon steel. Exceptional edge retention.',
    price: 600000,
    category: 'Kitchenware',
    imageUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800&q=80',
    inStock: true,
    colors: ['Damascus Pattern'],
    sizes: ['8-inch Gyuto'],
    rating: 4.6,
    reviewCount: 21,
    stockQuantity: 5,
  },
];

export const mockOrders = [
  {
    _id: 'order_1',
    buyer: 'user_buyer_1',
    shop: 'shop_3',
    items: [
      {
        product: 'prod_7',
        name: 'Speckled Coffee Mug',
        price: 65000,
        quantity: 2,
      },
    ],
    total: 130000,
    deliveryAddress: '123 Mango Avenue, Cebu City, Cebu 6000',
    trackingNumber: 'JNT123456789',
    courier: 'J&T',
    paymentMethod: 'cod',
    status: 'shipped',
    createdAt: '2026-06-10T10:30:00Z',
  },
  {
    _id: 'order_2',
    buyer: 'user_buyer_1',
    shop: 'shop_1',
    items: [
      {
        product: 'prod_1',
        name: 'Ochre Highlands Scarf',
        price: 18500,
        quantity: 1,
      },
    ],
    total: 18500,
    deliveryAddress: '123 Mango Avenue, Cebu City, Cebu 6000',
    trackingNumber: null,
    courier: null,
    paymentMethod: 'paymongo',
    status: 'pending',
    createdAt: '2026-06-12T14:15:00Z',
  },
  {
    _id: 'order_3',
    buyer: 'user_buyer_1',
    shop: 'shop_3',
    items: [
      {
        product: 'prod_7',
        name: 'Speckled Coffee Mug',
        price: 65000,
        quantity: 1,
      },
      {
        product: 'prod_9',
        name: 'Matte Charcoal Vase',
        price: 95000,
        quantity: 1,
      },
    ],
    total: 160000,
    deliveryAddress: '123 Mango Avenue, Cebu City, Cebu 6000',
    trackingNumber: 'ENT778899001',
    courier: 'Enterprise Cargo',
    paymentMethod: 'cod',
    status: 'delivered',
    createdAt: '2026-06-08T09:00:00Z',
  },
];
